let FalcorConstants = {
  CHANGE_EVENT: 'CHANGE_EVENT',
  FALCOR_GET_VALUE: 'FALCOR_GET_VALUE',
  FALCOR_GET: 'FALCOR_GET',
  FALCOR_SET_VALUE: 'FALCOR_SET_VALUE',
  FALCOR_SET: 'FALCOR_SET',
  FALCOR_CALL: 'FALCOR_CALL'
};

export default FalcorConstants;
